// Generated by CoffeeScript 1.3.3
var create_topic, focus_type, highlight_joined, more_posts, more_topic, scroll_view, set_avatar, set_name, set_padding, show_topic, slide_right, start_posts, sync_post;

create_topic = function() {
  var text;
  text = $('#create').val().trim();
  if (text.length > 0) {
    s.emit('create-topic', text);
  }
  $('#create').val('');
  return $('#create').fadeOut();
};

focus_type = function() {
  if ($('body').scrollLeft() > 100) {
    return $('body').animate({
      scrollLeft: 0
    }, function() {
      return $('#type').focus();
    });
  } else {
    return $('#type').focus();
  }
};

slide_right = function() {
  var left, screen_width;
  left = $('body').scrollLeft();
  screen_width = $(window).width();
  show(screen_width, left);
  if (left < 10) {
    return $('body').animate({
      scrollLeft: 2000 - screen_width
    });
  } else {
    return focus_type();
  }
};

set_name = function() {
  var name;
  name = $('#set-name').val();
  ls.name = name;
  return s.emit('set-name', name);
};

set_avatar = function() {
  ls.avatar = $('#set-avatar').val();
  $('#avatar').attr('src', ls.avatar);
  return s.emit('set-avatar', ls.avatar);
};

show_topic = function(list) {
  var end, topic_id;
  if (found(list)) {
    list.forEach(prepend_topic);
    end = list[0];
    topic_id = end.topic_id;
    s.emit('goto-topic', topic_id);
    return highlight_joined(topic_id);
  } else {
    return add_err({
      text: 'all listed'
    });
  }
};

start_posts = function(list) {
  $('#show').empty();
  return list.forEach(prepend_post);
};

sync_post = function(obj) {
  var elem, post_id, query;
  if (obj.topic_id != null) {
    post_id = obj.post_id;
    query = ".unit span[post_id='" + post_id + "']";
    elem = $(query);
    if (found(elem)) {
      return elem.text(obj.text);
    } else {
      return append_post(obj);
    }
  } else {
    add_err({
      text: 'topic_id not found..!'
    });
    return add_err({
      text: 'add topic first and click to join!'
    });
  }
};

scroll_view = function(direc) {
  var h, top;
  top = $('#show').scrollTop();
  h = $(window).height() - 100;
  if (direc === 'up') {
    return $('#show').animate({
      scrollTop: top - h
    }, 100);
  } else if (direc === 'down') {
    return $('#show').animate({
      scrollTop: top + h
    }, 100);
  }
};

highlight_joined = function(topic_id) {
  var query;
  query = "#inside .unit[topic_id='" + topic_id + "']";
  $('.joined').removeClass('joined');
  return $(query).addClass('joined');
};

more_posts = function(list) {
  if (found(list)) {
    return list.forEach(prepend_post);
  } else {
    return add_err({
      text: 'all posts listed'
    });
  }
};

set_padding = function() {
  var h, h1, h2;
  h = $(window).height();
  h1 = h * 0.2;
  h2 = h * 0.8;
  $('#show').css('padding', "" + h1 + "px 0px " + h2 + "px");
  return $('#inside').css('padding', "" + h1 + "px 0px " + h2 + "px");
};

more_topic = function(list) {
  if (found(list)) {
    return list.forEach(prepend_topic);
  } else {
    return add_err({
      text: 'all listed'
    });
  }
};
