// Generated by CoffeeScript 1.4.0
var bind_events;

bind_events = function() {
  $('#create').click(function(e) {
    return false;
  });
  $('body').click(function() {
    return $('#create').fadeOut();
  });
  $('#add').click(function() {
    return $('#create').fadeIn().focus() && false;
  });
  $('#create').keydown(function(e) {
    if (e.keyCode === 13) {
      create_topic();
      e.preventDefault();
      return false;
    }
  });
  $('body').keydown(function(e) {
    if (e.keyCode === 9) {
      slide_right();
      return e.preventDefault();
    } else if (e.keyCode === 33) {
      return scroll_view('up');
    } else if (e.keyCode === 34) {
      return scroll_view('down');
    }
  });
  $('#type').bind('input', function() {
    var text;
    focus_type();
    text = $('#type').val().trim();
    if (text.length > 0) {
      return s.emit('sync-post', text);
    }
  });
  $('#type').keydown(function(e) {
    var text;
    if (e.keyCode === 13) {
      text = $('#type').val().trim();
      if (text.length > 0) {
        s.emit('add-post', text);
      }
      return $('#type').val('');
    }
  });
  $('#set-name').bind('input', set_name);
  $('#set-avatar').bind('input', set_avatar);
  $('#toggle').click(function() {
    var width;
    width = $('#setting').width();
    if (width > 40) {
      $('#setting').animate({
        width: '40px'
      });
      return $('#toggle').attr('src', '../pics/arrow-left.png');
    } else {
      $('#setting').animate({
        width: '400px'
      });
      return $('#toggle').attr('src', '../pics/arrow-right.png');
    }
  });
  $('#inside').bind('scroll', function() {
    var elem, top, topic_id;
    top = $('#inside').scrollTop();
    if (top === 0) {
      elem = $('#inside .unit:first-child');
      topic_id = elem.attr('topic_id');
      return s.emit('more-topic', topic_id);
    }
  });
  $('#show').bind('scroll', function() {
    var elem, post_id, top;
    top = $('#show').scrollTop();
    if (top === 0) {
      elem = $('#show .unit:first-child').find('.text');
      post_id = elem.attr('post_id');
      return s.emit('more-posts', post_id);
    }
  });
  return $(window).resize(set_padding);
};
