// Generated by CoffeeScript 1.3.3
var bind_events;

bind_events = function() {
  $('#create').click(function(e) {
    return false;
  });
  $('body').click(function() {
    return $('#create').fadeOut();
  });
  $('#add').click(function() {
    return $('#create').fadeIn().focus() && false;
  });
  $('#create').keydown(function(e) {
    if (e.keyCode === 13) {
      create_topic();
      e.preventDefault();
      return false;
    }
  });
  $('body').keydown(function(e) {
    show(e.keyCode);
    if (e.keyCode === 9) {
      e.preventDefault();
      return slide_right();
    } else if (e.keyCode === 33) {
      return scroll_view('up');
    } else if (e.keyCode === 34) {
      return scroll_view('down');
    }
  });
  $('#type').bind('input', function() {
    var text;
    focus_type();
    text = $('#type').val().trim();
    if (text.length > 0) {
      return s.emit('sync-post', text);
    }
  });
  $('#type').keydown(function(e) {
    var text;
    if (e.keyCode === 13) {
      text = $('#type').val().trim();
      if (text.length > 0) {
        s.emit('add-post', text);
      }
      return $('#type').val('');
    }
  });
  $('#set-name').bind('input', set_name);
  $('#set-avatar').bind('input', set_avatar);
  return $('#toggle').click(function() {
    var width;
    width = $('#setting').width();
    if (width > 40) {
      return $('#setting').animate({
        width: '40px'
      });
    } else {
      return $('#setting').animate({
        width: '400px'
      });
    }
  });
};
