// Generated by CoffeeScript 1.3.3
var delay, err_tmpl, host, ls, make_err, nn, post_tmpl, put, repeat, s, show, time;

host = location.host;

s = io.connect("http://" + host + ":8000");

show = function(x) {
  return console.log(x);
};

repeat = function(t, f) {
  return setInterval(f, t);
};

delay = function(t, f) {
  return setTimeout(f, t);
};

ls = localStorage;

s.on('ready', function() {
  return show('ready');
});

post_tmpl = ".unit\n   img(src='#\{link\}').avatar\n   span.text= text";

put = jade.compile(post_tmpl);

err_tmpl = ".error\n  span.err-name :(\n  span.err-info= text";

make_err = jade.compile(err_tmpl);

nn = function(n) {
  if (n < 10) {
    return "0" + n;
  } else {
    return "" + n;
  }
};

time = function() {
  var h, m, now;
  now = new Date;
  h = nn(now.getHours());
  m = nn(now.getMinutes());
  s = nn(now.getSeconds());
  return "" + h + ":" + m + ":" + s;
};

$(function() {
  var focus_type, init, _i, _results;
  $('#set-name').bind('input', function() {
    var name;
    name = $(this).val();
    ls.name = name;
    return s.emit('set-name', name);
  });
  $('#set-avatar').bind('input', function() {
    var link;
    link = $(this).val();
    $('#avatar').attr('src', link);
    $('#avatar').attr('src');
    ls.avatar = link;
    return s.emit('set-avatar', link);
  });
  $('#toggle').click(function() {
    var width;
    width = $('#setting').width();
    show(width);
    if (width > 40) {
      return $('#setting').animate({
        width: '40px'
      });
    } else {
      return $('#setting').animate({
        width: '400px'
      });
    }
  });
  focus_type = function() {
    if ($('body').scrollLeft() > 100) {
      return $('body').animate({
        scrollLeft: 0
      }, function() {
        return $('#type').focus();
      });
    } else {
      return $('#type').focus();
    }
  };
  $('body').keydown(function(e) {
    var left, screen_width;
    if (e.keyCode === 9) {
      e.preventDefault();
      left = $('body').scrollLeft();
      screen_width = $(window).width();
      if (left < 10) {
        return $('body').animate({
          scrollLeft: 2000 - screen_width
        });
      } else {
        return focus_type();
      }
    }
  });
  $('#create').click(function(e) {
    return false;
  });
  $('body').click(function() {
    return $('#create').fadeOut();
  });
  $('#add').click(function() {
    return $('#create').fadeIn().focus() && false;
  });
  $('#create').keydown(function(e) {
    if (e.keyCode === 13) {
      s.emit('create', $('#create').val());
      $('#create').val('');
      return $('#create').fadeOut();
    }
  });
  $('#type').bind('input', function() {
    return focus_type();
  });
  (init = function() {
    if (ls.name != null) {
      $('#set-name').val(ls.name);
    }
    if (ls.avatar != null) {
      $('#set-avatar').val(ls.avatar);
      $('#set-avatar').trigger('input');
    }
    show('ok');
    return delay(800, focus_type);
  })();
  (function() {
    _results = [];
    for (_i = 1; _i <= 40; _i++){ _results.push(_i); }
    return _results;
  }).apply(this).forEach(function() {
    $('#show').append(put({
      link: ls.avatar,
      text: 'ffine'
    }));
    return $('#inside').append(put({
      link: ls.avatar,
      text: 'ffine'
    }));
  });
  repeat(200, function() {
    return $('#clock').text(time());
  });
  return [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].forEach(function() {
    return $('#msg').append(make_err({
      text: 'fake without any reason to prove you are wrong'
    }));
  });
});
