// Generated by CoffeeScript 1.3.3
var config, db, delay, io, mongo, posts, repeat, show, topic;

delay = function(t, f) {
  return setTimeout(f, t);
};

repeat = function(t, f) {
  return setInterval(f, t);
};

show = console.log;

config = require('./lib/config').config;

mongo = require('mongo-lite');

db = mongo.connect(config.mongo_url);

posts = db.collection('posts');

topic = db.collection('topic');

io = require('socket.io').listen(config.port, {
  origins: '*:*'
});

io.set('log level', 1);

io.sockets.on('connection', function(s) {
  return s.emit('ready');
});
