// Generated by CoffeeScript 1.3.3

$(function() {
  bind_events();
  if (ls.name != null) {
    $('#set-name').val(ls.name);
    s.emit('set-name', ls.name);
  }
  if (ls.avatar != null) {
    $('#set-avatar').val(ls.avatar);
    $('#set-avatar').trigger('input');
    return s.emit('set-avatar', ls.avatar);
  }
});
