// Generated by CoffeeScript 1.3.3
var draw_title, inpage, notify;

notify = {
  posts: 0,
  topic: 0
};

inpage = true;

$(window).focus(function() {
  inpage = true;
  $('title').text('talkpage');
  notify.posts = 0;
  notify.topic = 0;
  return show('focus');
});

$(window).blur(function() {
  show('blur');
  return inpage = false;
});

draw_title = function() {
  return $('title').text("" + notify.posts + " / " + notify.topic);
};

$(function() {
  bind_events();
  if (ls.name != null) {
    $('#set-name').val(ls.name);
    s.emit('set-name', ls.name);
  }
  if (ls.avatar != null) {
    $('#set-avatar').val(ls.avatar);
    $('#set-avatar').trigger('input');
    return s.emit('set-avatar', ls.avatar);
  }
});
