// Generated by CoffeeScript 1.4.0
var nn, time;

nn = function(n) {
  if (n < 10) {
    return "0" + n;
  } else {
    return "" + n;
  }
};

time = function() {
  var hou, min, now, sec;
  now = new Date;
  hou = nn(now.getHours());
  min = nn(now.getMinutes());
  sec = nn(now.getSeconds());
  return "" + hou + ":" + min + ":" + sec;
};

$(function() {
  return repeat(200, function() {
    return $('#clock').text(time());
  });
});
