// Generated by CoffeeScript 1.3.3
var add_err, add_post, append_topic, prepend_topic, tmpl;

tmpl = {};

tmpl.post = jade.compile(".unit\n   img(src='\#{avatar}',title='\#{name}',alt='\#{name}').avatar\n   .content\n     span.text(post_id='\#{post_id}',title='\#{time}')= text");

tmpl.topic = jade.compile(".unit(topic_id='\#{topic_id}')\n   img(src='\#{avatar}',title='\#{name}',alt='\#{name}').avatar\n   .content\n     span.text(title='\#{time}')= text");

tmpl.err = jade.compile(".error\n  span.err-name :(\n  span.err-info= text");

add_post = function(obj) {
  $('#show').append(tmpl.post(obj));
  if (!inpage) {
    notify.posts += 1;
    return draw_title();
  }
};

prepend_topic = function(obj) {
  $('#inside').prepend(tmpl.topic(obj));
  return $('#inside  .unit:first-child').click(function() {
    s.emit('goto-topic', obj.topic_id);
    return highlight_joined(obj.topic_id);
  });
};

add_err = function(obj) {
  var elem;
  $('#msg').append(tmpl.err(obj));
  elem = $('#msg .error:last-child');
  delay(4000, function() {
    return elem.slideUp(function() {
      return elem.remove();
    });
  });
  return focus_type();
};

append_topic = function(obj) {
  $('#inside').append(tmpl.topic(obj));
  $('#inside  .unit:last-child').click(function() {
    s.emit('goto-topic', obj.topic_id);
    return highlight_joined(obj.topic_id);
  });
  if (!inpage) {
    notify.topic += 1;
    return draw_title();
  }
};

/*
test_add_err = ->
  delay 1200, ->
    add_err text: 'test'

test_add_topic = ->
  add_topic
    link: 'http://tp1.sinaimg.cn/1651843872/180/5619585096/1'
    title: 'name'
    topic_id: '23345345'
    text: 'xvcxv'

test_add_post = ->
  add_post
    link: 'http://tp1.sinaimg.cn/1651843872/180/5619585096/1'
    title: 'name'
    post_id: '23345345'
    text: 'xvcxv'

repeat 1000, test_add_post
repeat 1000, test_add_topic
repeat 1000, test_add_err
*/

