// Generated by CoffeeScript 1.3.3
var delay, found, last, ls, repeat, show,
  __slice = [].slice;

show = function() {
  var x;
  x = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  return console.log.apply(console, x);
};

repeat = function(t, f) {
  return setInterval(f, t);
};

delay = function(t, f) {
  return setTimeout(f, t);
};

last = function(list) {
  var length;
  length = list.length;
  return list[length - 1];
};

found = function(list) {
  return list.length > 0;
};

ls = localStorage;
